"""changed relation

Revision ID: 02d906a5e14b
Revises: 29a9a696b57b
Create Date: 2022-03-23 14:57:47.059287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d906a5e14b'
down_revision = '29a9a696b57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'tests', ['test'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'test')
    # ### end Alembic commands ###
