"""nope

Revision ID: 060ea987494d
Revises: acf63ad2d0c7
Create Date: 2022-03-03 13:06:31.040037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060ea987494d'
down_revision = 'acf63ad2d0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
