"""changed relation

Revision ID: 09b691e69aac
Revises: 3a5c0003d7f6
Create Date: 2022-03-23 14:42:15.676439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b691e69aac'
down_revision = '3a5c0003d7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_test_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_test_fkey', 'questions', 'tests', ['test'], ['id'])
    # ### end Alembic commands ###
