"""added ordering

Revision ID: 19b83fb3ed6b
Revises: a98db6db95f6
Create Date: 2022-04-27 15:03:03.769806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b83fb3ed6b'
down_revision = 'a98db6db95f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
