"""added foreign key from tests to user, added published flag and published date

Revision ID: 1e7e45e70428
Revises: a4f520211263
Create Date: 2022-03-01 12:55:49.816897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7e45e70428'
down_revision = 'a4f520211263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('holder', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tests', 'users', ['holder'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'published_date')
    op.drop_column('tests', 'published')
    op.drop_column('tests', 'holder')
    # ### end Alembic commands ###
