"""added lazy load for question.test\

Revision ID: 1f729666af1d
Revises: 02d906a5e14b
Create Date: 2022-04-11 11:41:57.507137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f729666af1d'
down_revision = '02d906a5e14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_test_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'])
    op.drop_column('questions', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_fkey', 'questions', 'tests', ['test'], ['id'])
    op.drop_column('questions', 'test_id')
    # ### end Alembic commands ###
