"""changed relation

Revision ID: 29a9a696b57b
Revises: 09b691e69aac
Create Date: 2022-03-23 14:44:08.538349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a9a696b57b'
down_revision = '09b691e69aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
