"""refactored relation

Revision ID: 3a5c0003d7f6
Revises: a2d5a7901730
Create Date: 2022-03-22 18:49:21.426155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a5c0003d7f6'
down_revision = 'a2d5a7901730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_question', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_question', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('session_question', 'created_at')
    op.drop_column('session_question', 'id')
    op.drop_column('session_question', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_question', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session_question', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('session_question', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('session_question', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_question', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
