"""add user_id useranswers

Revision ID: 3e8d5e4b0c81
Revises: 4daf133f7099
Create Date: 2022-07-18 12:15:30.231976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8d5e4b0c81'
down_revision = '4daf133f7099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'user_id')
    # ### end Alembic commands ###
