"""Added is_admin flag

Revision ID: 4daf133f7099
Revises: f799c2561552
Create Date: 2022-04-28 17:38:05.835524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4daf133f7099"
down_revision = "f799c2561552"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
