"""added backrefs

Revision ID: 62335d355a13
Revises: 1f729666af1d
Create Date: 2022-04-11 13:08:50.722666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62335d355a13'
down_revision = '1f729666af1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answers_question_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.drop_column('answers', 'question')
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('test_id', sa.Integer(), nullable=True))
    op.drop_constraint('sessions_test_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_user_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_column('sessions', 'user')
    op.drop_column('sessions', 'test')
    op.add_column('tests', sa.Column('holder_id', sa.Integer(), nullable=True))
    op.drop_constraint('tests_holder_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'users', ['holder_id'], ['id'])
    op.drop_column('tests', 'holder')
    op.add_column('user_answers', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.add_column('user_answers', sa.Column('session_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_answers_session_fkey', 'user_answers', type_='foreignkey')
    op.drop_constraint('user_answers_answer_fkey', 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'user_answers', 'answers', ['answer_id'], ['id'])
    op.drop_column('user_answers', 'answer')
    op.drop_column('user_answers', 'session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('session', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_answers', sa.Column('answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key('user_answers_answer_fkey', 'user_answers', 'answers', ['answer'], ['id'])
    op.create_foreign_key('user_answers_session_fkey', 'user_answers', 'sessions', ['session'], ['id'])
    op.drop_column('user_answers', 'session_id')
    op.drop_column('user_answers', 'answer_id')
    op.add_column('tests', sa.Column('holder', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_holder_fkey', 'tests', 'users', ['holder'], ['id'])
    op.drop_column('tests', 'holder_id')
    op.add_column('sessions', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_fkey', 'sessions', 'users', ['user'], ['id'])
    op.create_foreign_key('sessions_test_fkey', 'sessions', 'tests', ['test'], ['id'])
    op.drop_column('sessions', 'test_id')
    op.drop_column('sessions', 'user_id')
    op.add_column('answers', sa.Column('question', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_fkey', 'answers', 'questions', ['question'], ['id'])
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
