"""refactored relation

Revision ID: a2d5a7901730
Revises: b2e9c88a3056
Create Date: 2022-03-22 18:46:12.854817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d5a7901730'
down_revision = 'b2e9c88a3056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
