"""added questions id for user answers

Revision ID: a3d5648c8fcf
Revises: 3e8d5e4b0c81
Create Date: 2022-07-18 17:20:39.914234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d5648c8fcf'
down_revision = '3e8d5e4b0c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'question_id')
    # ### end Alembic commands ###
