"""fix bugs in models, relations to user

Revision ID: a4b3d399fb3d
Revises: 7f9557779545
Create Date: 2022-03-09 12:06:35.889626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b3d399fb3d'
down_revision = '7f9557779545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
