"""added ordering

Revision ID: a98db6db95f6
Revises: a13a055d34d1
Create Date: 2022-04-27 14:45:47.325416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98db6db95f6'
down_revision = 'a13a055d34d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('ordering', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['ordering'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'ordering')
    # ### end Alembic commands ###
