"""added moderator

Revision ID: ab8f94d6e956
Revises: dd7f6733b3f6
Create Date: 2022-09-01 10:54:00.469490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8f94d6e956'
down_revision = 'dd7f6733b3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    # ### end Alembic commands ###
