"""deleted unique constraint for questions oredring

Revision ID: c1e30ba23aa7
Revises: 19b83fb3ed6b
Create Date: 2022-04-28 12:34:53.620878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e30ba23aa7'
down_revision = '19b83fb3ed6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_ordering_key', 'questions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('questions_ordering_key', 'questions', ['ordering'])
    # ### end Alembic commands ###
