"""Hello world

Revision ID: e29637ad9dba
Revises: 06af7f5836dc
Create Date: 2022-03-03 09:54:22.770096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29637ad9dba'
down_revision = '06af7f5836dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'title')
    # ### end Alembic commands ###
