"""added cascade deleting

Revision ID: f799c2561552
Revises: 3453bb53fafe
Create Date: 2022-04-28 17:09:57.259651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f799c2561552"
down_revision = "3453bb53fafe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("answers_question_id_fkey",
                       "answers", type_="foreignkey")
    op.create_foreign_key(
        None, "answers", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("images_question_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        None, "images", "questions", ["question"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("questions_test_id_fkey",
                       "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "tests", ["test_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "session_question_session_id_fkey", "session_question", type_="foreignkey"
    )
    op.drop_constraint(
        "session_question_question_id_fkey", "session_question", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "session_question",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "session_question", "sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("sessions_test_id_fkey", "sessions", type_="foreignkey")
    op.drop_constraint("sessions_user_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(
        None, "sessions", "tests", ["test_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("tests_holder_id_fkey", "tests", type_="foreignkey")
    op.create_foreign_key(
        None, "tests", "users", ["holder_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "user_answers_answer_id_fkey", "user_answers", type_="foreignkey"
    )
    op.drop_constraint(
        "user_answers_session_id_fkey", "user_answers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_answers", "sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_answers", "answers", ["answer_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_answers", type_="foreignkey")
    op.drop_constraint(None, "user_answers", type_="foreignkey")
    op.create_foreign_key(
        "user_answers_session_id_fkey",
        "user_answers",
        "sessions",
        ["session_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_answers_answer_id_fkey", "user_answers", "answers", [
            "answer_id"], ["id"]
    )
    op.drop_constraint(None, "tests", type_="foreignkey")
    op.create_foreign_key(
        "tests_holder_id_fkey", "tests", "users", ["holder_id"], ["id"]
    )
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_user_id_fkey", "sessions", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "sessions_test_id_fkey", "sessions", "tests", ["test_id"], ["id"]
    )
    op.drop_constraint(None, "session_question", type_="foreignkey")
    op.drop_constraint(None, "session_question", type_="foreignkey")
    op.create_foreign_key(
        "session_question_question_id_fkey",
        "session_question",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.create_foreign_key(
        "session_question_session_id_fkey",
        "session_question",
        "sessions",
        ["session_id"],
        ["id"],
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_test_id_fkey", "questions", "tests", ["test_id"], ["id"]
    )
    op.drop_constraint(None, "images", type_="foreignkey")
    op.create_foreign_key(
        "images_question_fkey", "images", "questions", ["question"], ["id"]
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        "answers_question_id_fkey", "answers", "questions", [
            "question_id"], ["id"]
    )
    # ### end Alembic commands ###
